[package]
name = "ez_term"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "example"
path = "Examples/full_example.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"